### ISSUE TITLE
Add an example to README.md

### ISSUE THREAD

**Issue by lack** [Quessou/qssnotify#2]
I think I understand what this does because I saw your Mastodon post that said something about reminding you to take regular care of yourself.

I think adding something like that to the README would help clarify this a bit, as would an example sentence file.

**Comment by Quessou** [comment]
Thank you for opening an issue !

My README.md is probably awful, since it's the first one I write for some project which can be used by anyone.

There's no need to write such a file by hand actually, just call `qssnotify --add` will open a text editor, you can then write your sentence and it will add it automatically to the file :) 

I guess I'll just write more stuff in the README !

**Comment by Quessou** [comment]
I've added more stuff, do not hesitate to tell me if something is still unclear ! :)

I'd love to see this little thingy accessible to the largest amount of people tbh

**Comment by lack** [comment]
Looks awesome! Thanks!

**Comment by Quessours** [comment]
I'll close the issue then :)
Do not hesitate to post other issues !
